### PR TITLE
Round 2

### PR DESCRIPTION
**Pull request by ScottDTA**
Was able to get 3 more mods this afternoon.

### CODE REVIEW

**Comment by Shoeboxam** [comment]
This is useful, but there may be a faster approach to port files from older versions to 1.18. I wrote this python package here:
https://github.com/Soartex-Modded/Resource-Wrangler

It's been a year since I've run it, so some API debugging may be necessary. But it should hopefully give us a good baseline for 1.18.

**Comment by ScottDTA** [comment]
Yes, I looked at it.  All of the ones I've done so far, the texture names have changed significantly or are not in the previous versions.  Structurize was the only exception, but only had the 3 items that were done.

**Review by Shoeboxam — APPROVED** [review]
Thank you!

**Comment by Shoeboxam** [comment]
The approach in that linked repo doesn't care about file names, it ports based on file hashes. Which means there can be false negatives, when a mod author compresses their files are tweaks a pixel. Regardless, I'll try to find some time to run it for 1.18. It by no means handles everything, but it should help cut down on the work.

**Comment by ScottDTA** [comment]
good to know.   I'll keep working on some of the mods that I didn't see in previous versions or were broken in past versions.

**Pull request merged**
